version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=police_ops
      - MYSQL_USER=fritz.furittsu
      - MYSQL_PASSWORD=CanNeverGu355Th15Passw0rD 
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    image: php:apache
    volumes:
      - "./web:/var/www/html"
    ports:
      - 80:80
    command: /bin/sh -c "docker-php-ext-install mysqli pdo_mysql && apache2-foreground"
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
    depends_on:
      - www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306